manual_dic = {
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520238200":["python, data-science, machine-learning, statistics, deep-learning"],
    "520197073":["data-science rl dsml"],
    "520265422":["javascript, css, python, git, linux, html, php, data-science, machine-learning, django, typescript, sql, scikit-learn, selenium, pandas, seaborn, kivy, linux-commands, matplotlib-pyplot, linux-paths"],
    "750847305":["react, open-source, data-science, data, sql, dashboard, analytics, javascript-framework, exploratory-data-analysis, svelte data-visualization, self-hosted, data-engineering, business-intelligence, data-analytics, data-analysis, tailwindcss, embedded-analytics, duckdb, data-app"],
    
    "749049312":["data-science, machine-learning, data-mining, awesome, deep-learning, time-series, dataset, awesome-list, segmentation, motion-capture, unsupervised-learning, time-series-analysis, anomaly-detection, change-point-detection, time-series-models, paper-list, time-series-segmentation, multivariate-time-series, univariate-time-series"],
    
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    "520273044":["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"]
  
              }