manual_dic = {
    520273044:["python", "rust" "data-science", "machine-learning", "version-control", "artificial-intelligence"],
    520197073:["data-science", "rl", "dsml"],
    520265422:["javascript", "css", "python", "git", "linux", "html", "php", "data-science", "machine-learning", "django", "typescript", "sql", "scikit-learn", "selenium", "pandas", "seaborn", "kivy", "linux-commands", "matplotlib-pyplot", "linux-paths"],
    520238200:["python", "data-science", "machine-learning", "statistics", "deep-learning"],
    750847305:["react", "open-source", "data-science", "data", "sql", "dashboard", "analytics", "javascript-framework", "exploratory-data-analysis", "svelte data-visualization", "self-hosted", "data-engineering", "business-intelligence", "data-analytics", "data-analysis", "tailwindcss", "embedded-analytics", "duckdb", "data-app"],
    749049312:["data-science", "machine-learning", "data-mining", "awesome", "deep-learning", "time-series", "dataset", "awesome-list", "segmentation", "motion-capture", "unsupervised-learning", "time-series-analysis", "anomaly-detection", "change-point-detection", "time-series-models", "paper-list", "time-series-segmentation", "multivariate-time-series", "univariate-time-series"],
    751135933:["agent", "data-science", "table data-analytics", "large-language-models", "llm", "prompt-engineering", "instruction-tuning"],
    744634700:["data-science", "kafka monitoring", "timeseries", "grafana", "jupyter-notebook", "pandas", "telegraf", "kafka-connect", "timeseries-database", "timeseries-analysis", "timeseries-forecasting", "questdb", "polars"],
    748935547:["python", "docker", "data-science", "rstats"],
    740929773: ["python", "data-science", "machine-learning", "plotly", "jupyter-notebook", "pandas", "data-visualization", "seaborn", "artificial-intelligence", "matplotlib"],
    748661381: ["python", "data-science", "machine-learning", "deep-learning", "openai", "neural-networks", "google-bert", "huggingface", "transformers-models", "large-language-models", "generative-ai", "75hardchallenge", "genai-course", "llm-course"],
    745017882: ["python", "data-science", "machine-learning", "sql", "deep-learning", "algorithms-and-data-structures"],
    747899678: ["python", "data-science", "pandas", "data-visualization", "matplotlib", "dataframe"],
    748386702: ["iot", "data-science", "telegram-bot", "data-visualization", "smart-home", "openai", "smart-grids", "telegram-bot-api", "energy-data", "iot-application", "digitaltwins", "llm"],
    749425870: ["python", "data-science", "machine-learning", "ml", "logistic-regression", "capstone-project"],
    740628369: ["data-science", "machine-learning", "time-series", "interview-practice", "coding-interviews", "interview-preparation", "technical-interview-questions", "machine-learning-interview", "data-science-interview", "data-scientist-interview", "software-engineer-interview", "data-science-interview-questions", "coding-interview-questions", "machine-learning-interview-questions", "ai-interview-questions", "machine-learning-and-data-science", "time-series-interview-questions", "time-series-questions", "time-series-tech-interview"],
    749216535: ["python", "data-science", "data", "ml", "library-management", "mlops", "gpt-4o"],
    741425548: ["python", "data-science", "data-visualization", "seaborn", "data-analysis", "dotplot", "matplotlib-pyplot", "matplotlib-python", "seaborn-plots", "dotplots", "dot-chart", "strip-plots"],
    747498791: ["agent", "data-science", "automation", "analytics", "openai", "multiagent", "gpt", "llm"],
    745558084: ["website", "data-science", "r", "teaching-materials", "quarto", "code-tutorials"],
    740631372: ["data-science", "machine-learning", "interview-practice", "unsupervised-learning", "coding-interviews", "interview-preparation", "technical-interview-questions", "machine-learning-interview", "data-science-interview", "data-scientist-interview", "software-engineer-interview", "data-science-interview-questions", "coding-interview-questions", "machine-learning-interview-questions", "ai-interview-questions", "machine-learning-and-data-science", "unsupervised-learning-interview-questions", "unsupervised-learning-questions", "unsupervised-learning-tech-interview"],
    747205577: ["python", "data-science", "numpy", "web-scraper", "pandas", "data-analysis", "bs4", "playwright"],
    741461792: ["data-science", "deep-neural-networks", "signal-processing", "exploratory-data-analysis", "neuroscience", "data-visualization", "eeg", "healthcare", "data-analysis", "eeg-signals", "critical-care", "medical-research"],
    748124687: ["nlp", "go", "bash", "golang", "data-science", "machine-learning", "automation", "deep-neural-networks", "deep-learning", "algorithms", "analytics", "analysis", "text-classification", "machine-learning-algorithms", "image-processing", "tts", "voice-recognition", "image-classification", "decision-trees", "anomaly-detection"],
    741696713: ["react", "javascript", "python", "c", "data-science", "machine-learning", "r", "matlab", "learn-to-code", "data-analysis", "shell-script"],
    744219457: ["python", "data-science", "machine-learning", "ai", "classification"],
    740632255: ["data-science", "machine-learning", "xgboost", "interview-practice", "coding-interviews", "interview-preparation", "technical-interview-questions", "machine-learning-interview", "data-science-interview", "data-scientist-interview", "software-engineer-interview", "data-science-interview-questions", "coding-interview-questions", "machine-learning-interview-questions", "ai-interview-questions", "machine-learning-and-data-science", "xgboost-interview-questions", "xgboost-questions", "xgboost-tech-interview"],
    746881096: ["data-science", "healthcare", "attacks", "warzone"],
    742225471: ["data-science", "social-sciences", "education-materials", "course-repository"],
    743389956: ["python", "data-science", "machine-learning", "artificial-intelligence", "stock-market", "financial-analysis", "streamlit"],
    742748795: ["data-science", "twitter-sentiment-analysis"],
    749824337: ["python", "api", "data-science", "deep-learning", "artificial-intelligence", "huggingface", "large-language-models", "llm", "chatgpt", "llm-training"],
    751266419: ["python", "data-science", "qlearning", "dqn", "supervised-learning", "sumo", "sarsa-learning", "renforcement-learning", "stablebaselines3", "sumo-rl"],
    744613283: ["python", "data-science", "eda", "data-visualization"],
    744302376: ["data-science", "machine-learning", "statistics", "database"],
    751009758: ["python", "data-science", "powerbi", "ciencia-de-dados", "analise-de-dados"],
    747526318: ["data-science"],
    750824445: ["data-science", "natural-language-processing", "neural-network", "tensorflow", "speech-recognition", "music-genre-classification", "lyrics-analysis"],
    747144802: ["finance", "data-science", "machine-learning", "banking", "hyperparameter-optimization", "predictive-modeling", "risk-assessment", "credit-risk"],
    741371073: ["python", "data-science", "machine-learning", "streamlit"],
    748552140: ["python", "data-science", "data", "log", "scikit-learn", "transformer"],
    746881230: ["python", "data-science", "data", "html5", "data-visualisation", "data-collection", "data-cleaning"],
    745730457: ["data-science", "machine-learning", "artificial-intelligence", "ensemble-learning"],
    748279681: ["python", "finance", "data-science", "machine-learning", "numpy", "machine-learning-algorithms", "pandas", "data-engineering", "stock-market", "stock-price-prediction", "data-analysis", "stocks", "financial-analysis", "portefolio", "yfinance"],
    746802947: ["data-science", "machine-learning", "csv", "artificial-intelligence", "dataanalytics"],
    740630831: ["data-science", "machine-learning", "interview-practice", "transfer-learning", "coding-interviews", "interview-preparation", "technical-interview-questions", "machine-learning-interview", "data-science-interview", "data-scientist-interview", "software-engineer-interview", "data-science-interview-questions", "coding-interview-questions", "machine-learning-interview-questions", "ai-interview-questions", "machine-learning-and-data-science", "transfer-learning-interview-questions", "transfer-learning-questions", "transfer-learning-tech-interview"],
    742559413: ["data-science", "machine-learning", "stress", "signal-processing", "research-project", "feature-engineering", "mental-health", "datadriven"]
    }